site_name: RAstro
site_author: Duncan Eddy
site_description: RAstro astrodynamics - high performance, easy to learn, and
  fast to code, ready for production
site_url: https://github.com/duncaneddy/rastro
repo_url: https://github.com/duncaneddy/rastro
edit_uri: ''

theme:
  name: material
  custom_dir: overrides
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - python
  palette:
    - scheme: default
      primary: orange
      accent: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: slate
      primary: orange
      accent: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  logo: img/icon.svg
  favicon: img/favicon.png
  language: en
  features:
    - navigation.instant
    - navigation.top

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

nav:
  - RAstro: index.md
  - installation.md
  - User Guide:
      - user_guide/index.md
      - user_guide/constants.md
      - Data:
        - user_guide/data/index.md
        - user_guide/data/eop.md
      - Time [WIP]:
        - user_guide/time/index.md
        - user_guide/time/epoch.md
      - Orbits:
        - user_guide/orbits/index.md
        - user_guide/orbits/properties.md
        - user_guide/orbits/anomalies.md
  - Reference:
      - reference/index.md
      - Orbits:
          - reference/orbits/index.md
          - reference/orbits/two_body_problem.md
          - reference/orbits/orbital_elements.md
  - Python API Reference:
      - python_api/index.md
      - python_api/constants.md
      - python_api/orbits.md
  - glossary.md
  - developer_guide.md
  - roadmap.md

extra_javascript:
  - js/mathjax.js
  - https://cdn.plot.ly/plotly-latest.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js