[package]
name = "rastro"
version = "0.1.0"
authors = ["Duncan Eddy <duncan.eddy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsofa = {version = "^0.2.0"}
nalgebra = {version = "^0.23.2"}

[dev-dependencies]
approx = "^0.4.0"