name: Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  test-rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Change to nightly (TODO - Remove when BTreeMap cursor is stablilized)
        run: rustup default nightly
      - run: cargo test
  test-python:
    runs-on: ${{ matrix.os }}
    needs: test-rust
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./rastro_python/requirements-dev.txt
      - name: Install package
        run: python -m pip install -e ./rastro_python
      - name: Run Tests
        run: pytest
# Uncomment this to update docs on every commit. Only used for fast documentation updating outside
# of release cycle.
#  docs:
#    runs-on: ubuntu-latest
#    needs: test-python
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python 3.6
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.6
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          ./docs/build.sh install
#      - name: Update index from README
#        run: |
#          cp README.md docs/en/docs/index.md
#      - name: Build docs
#        run: ./docs/build.sh build
#      - name: Deploy docs
#        run: ./docs/build.sh publish